name: Build and Release

on:
  push:
    tags:
    - '**'

jobs:
  build:
    uses: otter-eng/workflows/.github/workflows/build-image.yaml@main
    with:
      environment: prod
      name: por-verifier-server
      tag: ${{ github.ref_name }}
    permissions:
      contents: read
      id-token: write

  release:
    needs: build
    uses: otter-eng/workflows/.github/workflows/deploy-to-gke.yaml@main
    with:
      environment: prod
      containers: "por-verifier-server=por-verifier-server:${{ github.ref_name }}"
    permissions:
      contents: read
      id-token: write